name: Release Electron

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create Release
        run: gh release create ${{ github.ref }} --title ${{ github.ref_name }} --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build
        run: |
          npm clean-install
          sh build.sh

      - name: Upload Release Asset
        run: |
          gh release upload ${{ github.ref_name }} dist/rwa-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    needs: release
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache npm
        uses: actions/cache@v2
        with:
          path: ${{ env.LOCALAPPDATA }}/npm-cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build
        run: |
          npm clean-install
          sh build.sh

      - name: Upload Release Asset
        run: |
          gh release upload ${{ github.ref_name }} dist/rwa-*.exe dist/rwa-*.7z
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    needs: release
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build
        run: |
          npm clean-install
          sh build.sh

      - name: Upload Release Asset
        run: |
          gh release upload ${{ github.ref_name }} dist/rwa-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
